# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'VendingMachine' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VendingMachine
  pod 'Hue','~> 1.1.0'
  pod 'Google','~>3.0'
end
